version: '3'
services:
  user-management-api-service:
    image: ${DOCKER_REGISTRY-}user-management-api-service
    build:
      context: .
      dockerfile: src/UserManagement/UserManagement.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32701:8080"
    networks:
      - asisto-tad-network
  api-gateway-service:
    image: ${DOCKER_REGISTRY-}api-gateway-service
    build:
      context: .
      dockerfile: api-gateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32710:8080"
    networks:
      - asisto-tad-network
  swagger-combine:
    image: swaggerql/swagger-combine-ui
    ports:
      - "32799:3000"
    networks:
      - asisto-tad-network
    volumes:
      - ./swagger-config.yaml:/app/swagger.yaml
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "32700:80"
    networks:
      - asisto-tad-network
networks:
  asisto-tad-network:
    driver: bridge